; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; 串口监视器波特率 (必须与代码 Serial.begin 保持一致)
monitor_speed = 115200

; === 关键修改：OTA 分区方案 ===
; 使用 min_spiffs.csv 可以最大化代码空间 (App0: 1.9MB, App1: 1.9MB)
; 这样能保证有足够的空间下载新固件
board_build.partitions = min_spiffs.csv

; === 核心库依赖 ===
lib_deps =
    ; 1. MQTT 库 (Nick O'Leary 出品，最经典好用)
    knolleary/PubSubClient @ ^2.8
    
    ; 2. ADXL355 库 (根据你引用的头文件 PL_ADXL355.h，应该是这个库)
   plasmapper/PL ADXL355 @ ^1.3.0   
